# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Topics
    url: tags/
    weight: 20
  - name: Uses
    url: uses/
    weight: 30
  - name: Home
    url: /
    weight: 10
  - name: MyNetflix
    url: /myNetflix/
    weight: 30
  - name: study
    url: /study/
    weight: 30
