# Navigation Links
#   The weight parameter defines the order that the links will appear in.
main:
  - name: 소개
    identifier: introduction
    url: introduction/
    weight: 10
  - name: 나에 대한 소개
    parent: introduction
    url: introduction/about-me
    weight: 10
  - name: 기술
    parent: introduction
    url: introduction/skills
    weight: 20
          
  - name: 블로그
    identifier: blog
    url: blog/
    weight: 30
  - name: 챌린지 및 대회
    parent: blog
    url: blog/challenges
    weight: 10
  - name: 기록
    parent: blog
    url: blog/challenges
    weight: 20

  - name: 홈
    url: /
    weight: 50

  - name: 넷플릭스 
    identifier: mynetflix
    url: mynetflix/
    weight: 70
  - name: 한국
    parent: mynetflix
    url : mynetflix/korean-dramas/
    weight: 10
  - name: 서부
    parent: mynetflix
    url: mynetflix/western-shows/
    weight: 20

  - name: 공부
    identifier: study
    url: study/
    weight: 90
  - name: 프로젝트
    parent: study
    url: study/project
    weight: 10
  - name: 알고리즘 및 문제해결
    parent: study
    url: study/problemsolving
    weight: 20
