# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Uses
    url: uses/
    weight: 10

  # 추가된 것!
  - name: Introduction
    identifier: introduction
    url: introduction/
    weight: 20
  - name: About Me
    parent: introduction
    url: introduction/about-me
    weight: 10
  - name: Skills
    parent: introduction
    url: introduction/skills
    weight: 20

  - name: Home
    url: /
    weight: 30

  - name: MyNetflix
    identifier: mynetflix
    url: mynetflix/
    weight: 40
  - name: "Korean Dramas"
    parent: mynetflix
    url : mynetflix/korean-dramas/
    weight: 10
  - name: "Western Shows"
    parent: mynetflix
    url: mynetflix/western-shows/
    weight: 20

  - name: Study
    identifier: study
    url: study/
    weight: 50
  - name: Project
    parent: study
    url: study/project
    weight: 10
  - name: ProblemSolving
    parent: study
    url: study/problemsolving
    weight: 20