# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Topics
    url: tags/
    weight: 20
  - name: Uses
  
    url: uses/
    weight: 30
  - name: Home
    url: /
    weight: 10
  - name: MyNetflix
    url: /mynetflix/
    weight: 40
    # children: #하위 메뉴 추가
    #   - name: "Korean Dramas"
    #     url : /mynetflix/korean-dramas/
    #     weight: 10
    #   - name: "Western Shows"
    #     url: /mynetflix/western-shows/
    #     weight: 20
  - name: study
    url: /study/
    weight: 50
