# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Topics
    url: tags/
    weight: 20
  - name: Uses
  
    url: uses/
    weight: 30
  - name: Home
    url: /
    weight: 10
  - name: MyNetflix
    identifier: mynetflix
    url: mynetflix/
    weight: 40
  - name: "Korean Dramas"
    parent: mynetflix
    url : mynetflix/korean-dramas/
    weight: 10
  - name: "Western Shows"
    parent: mynetflix
    url: mynetflix/western-shows/
    weight: 20
  - name: study
    url: study/
    weight: 50
